export const cards = [
  {
    id: 1,
    theme: "Web Disign",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 3,
    topic: "Web Disign",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 4,
    topic: "Copywritting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 5,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 6,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Copywritting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 9,
    topic: "Web Disign",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 10,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестированиие",
  },
  {
    id: 10,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  }
];
